language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

jobs:
  include:
    - stage: check
      name: Tests
      script: cargo test
    # - stage: check
    #   name : Rustfmt
    #   install: rustup component add rustfmt
    #   script: cargo fmt -- --check
    # - stage: check
    #   name: Clippy
    #   install: rustup component add clippy
    #   script: cargo clippy
stages:
  - name: check

# branches:
#   only:
#     - master

notifications:
  email:
    on_success: never

