[package]
name = "rumqtt"
version = "0.1.0"
authors = ["raviteja <k.teza1@gmail.com>"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-current-thread = "0.1"
bytes = "0.4"
futures = "0.1"
log = "0.4"
failure = "0.1"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }