[package]
name = "rumqtt"
version = "0.30.0"
authors = ["raviteja <k.teza1@gmail.com>"]

[dependencies]
tokio = "0.1"
tokio-timer = "0.2.7"
tokio-io = "0.1"
tokio-codec = "0.1"
tokio-tls = "0.2"
bytes = "0.4"
futures = "0.1"
crossbeam-channel = "0.3"
log = "0.4"
failure = "0.1"
derive_more = "0.13"
pretty_env_logger = "0.2"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }

[dependencies.native-tls]
version = "0.2"
optional = true

[dependencies.tokio-rustls]
version = "0.8"
optional = true

[dependencies.webpki]
version = "0.18"
optional = true

[dependencies.jsonwebtoken]
version = "5.0.1"
optional = true

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.serde]
version = "1"
optional = true

[dependencies.serde_derive]
version = "1"
optional = true

[dev-dependencies]
envy = "0.3"
serde = "1"
serde_derive = "1"

[features]
default = ["rustls", "jwt"]
rustls = ["tokio-rustls", "webpki"]
jwt = ["jsonwebtoken", "chrono", "serde", "serde_derive"]
nativetls = ["native-tls"]