[package]
name = "rumqtt"
version = "0.12.1"
authors = ["tekjar <k.teza1@gmail.com>"]

[dependencies]
rand = "0.3"
quick-error = "1.1"
log = "0.4"
mqtt311 = "0.1"
openssl = { version = "0.9" }
threadpool = "1"
chrono = "0.4"
jsonwebtoken = "2"
serde = "1"
serde_derive = "1"

[dev-dependencies]
pretty_env_logger = "0.1"
